version: "3"

services:
  fastapi:
    image: "api_fastapi:lastest"
    container_name: "fastapi"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mariadb
    container_name: fastapi_db
    ports:
        - 8080:8080
    restart: always
    env_file:
      - .env
